var drawingCanvas,drawingCanvasOnepage;function handleImage(b){var g=new FileReader;g.onload=function(b){var g=new Image;g.onload=function(){var b=new fabric.Image(g,{top:100,left:100});"oneside"==viewBox.mode?drawingCanvasOnepage.add(b):drawingCanvas.add(b)};g.src=b.target.result};g.readAsDataURL(b.target.files[0])}
function saveDrawingData(){drawingData[currentPageIdx]="oneside"==viewBox.mode?drawingCanvasOnepage.toJSON():drawingCanvas.toJSON();localStorage.setItem("drawing_"+epub_code,JSON.stringify(drawingData))}function disableSelectObject(){drawingCanvas.forEachObject(function(b){b.selectable=!1})}function disableSelectObjectOnepage(){drawingCanvasOnepage.forEachObject(function(b){b.selectable=!1})}
function setLineWidth(b){for(var g=1;5>g;g++)g==b?$("#btn_drawing_linewidth"+g).addClass("on"):$("#btn_drawing_linewidth"+g).removeClass("on")}function selectedMenu(b){1==b?($("#btn_drawing_draw").removeClass("on"),$("#btn_drawing_selection").addClass("on"),$(".blush_line").addClass("select_line"),$(".drawing_disable").show()):($("#btn_drawing_draw").addClass("on"),$("#btn_drawing_selection").removeClass("on"),$(".blush_line").removeClass("select_line"),$(".drawing_disable").hide())}
function setAlpha(b){$(".oper_value").text(b)}
function setPenMenu(b){switch(b){case 1:$("#btn_drawing_line").addClass("on");$("#btn_drawing_pencil").removeClass("on");$("#btn_drawing_highlight").removeClass("on");$("#btn_drawing_eraser").removeClass("on");$(".drawing_text").removeClass("on");setLineWidth(1);break;case 2:$("#btn_drawing_line").removeClass("on");$("#btn_drawing_pencil").addClass("on");$("#btn_drawing_highlight").removeClass("on");$("#btn_drawing_eraser").removeClass("on");$(".drawing_text").removeClass("on");setLineWidth(1);break;
case 3:$("#btn_drawing_line").removeClass("on");$("#btn_drawing_pencil").removeClass("on");$("#btn_drawing_highlight").addClass("on");$("#btn_drawing_eraser").removeClass("on");$(".drawing_text").removeClass("on");setLineWidth(4);break;case 4:$("#btn_drawing_line").removeClass("on");$("#btn_drawing_pencil").removeClass("on");$("#btn_drawing_highlight").removeClass("on");$("#btn_drawing_eraser").addClass("on");$(".drawing_text").removeClass("on");break;case 6:$("#btn_drawing_line").removeClass("on"),
$("#btn_drawing_pencil").removeClass("on"),$("#btn_drawing_highlight").removeClass("on"),$("#btn_drawing_eraser").removeClass("on"),$(".drawing_text").addClass("on")}}function hideTextAlert(){$(".drawing_text_on").hide()}
function setSelectionMode(b){b?(drawingCanvasOnepage.isDrawingMode=!1,drawingCanvasOnepage.selection=!0,drawingCanvas.isDrawingMode=!1,drawingCanvas.selection=!0,"oneside"==viewBox.mode?drawingCanvasOnepage.forEachObject(function(b){b.selectable=!0}):drawingCanvas.forEachObject(function(b){b.selectable=!0}),drawingCanvasOnepage.renderAll(),drawingCanvas.renderAll()):(drawingCanvas.isDrawingMode=!1,drawingCanvas.selection=!1,drawingCanvas.forEachObject(function(b){b.selectable=!1}),drawingCanvas.renderAll(),
drawingCanvasOnepage.isDrawingMode=!1,drawingCanvasOnepage.selection=!1,drawingCanvasOnepage.forEachObject(function(b){b.selectable=!1}),drawingCanvasOnepage.renderAll())}
(function(){var b,g,l,m,n,p,q,r,t,u,e=1,f="line";drawingCanvas=this.__canvas=new fabric.Canvas("drawingCanvas",{isDrawingMode:!1,selection:!1,preserveObjectStacking:!0});drawingCanvasOnepage=new fabric.Canvas("drawingCanvasOnepage",{isDrawingMode:!1,selection:!1,preserveObjectStacking:!0});fabric.Object.prototype.transparentCorners=!1;fabric.Object.prototype.cornerSize=3;document.getElementById("drawing-mode-options");var d=document.getElementById("drawing-color");document.getElementById("btn_drawing_line").onclick=
function(){setSelectionMode(!1);drawingCanvas.isDrawingMode=!1;drawingCanvas.selection=!1;f="line";e=1;drawingCanvas.renderAll();drawingCanvasOnepage.isDrawingMode=!1;drawingCanvasOnepage.selection=!1;f="line";e=1;drawingCanvasOnepage.renderAll();hideTextAlert();setPenMenu(1)};drawingCanvas.on("object:selected",function(a){null!=drawingCanvas.getActiveObject()&&drawingCanvas.getActiveObject().remove()});drawingCanvasOnepage.on("object:selected",function(a){null!=drawingCanvasOnepage.getActiveObject()&&
drawingCanvasOnepage.getActiveObject().remove()});document.getElementById("btn_drawing_pencil").onclick=function(){setSelectionMode(!1);e=1;drawingCanvas.isDrawingMode=!0;drawingCanvas.selection=!1;drawingCanvas.freeDrawingBrush=new fabric.PencilBrush(drawingCanvas);drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvas.freeDrawingBrush.width=parseInt(e,1)||1;drawingCanvas.renderAll();drawingCanvasOnepage.isDrawingMode=!0;drawingCanvasOnepage.selection=!1;drawingCanvasOnepage.freeDrawingBrush=
new fabric.PencilBrush(drawingCanvasOnepage);drawingCanvasOnepage.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvasOnepage.freeDrawingBrush.width=parseInt(e,1)||1;drawingCanvasOnepage.renderAll();hideTextAlert();setPenMenu(2)};document.getElementById("btn_drawing_highlight").onclick=function(){setSelectionMode(!1);e=30;drawingCanvas.isDrawingMode=!0;drawingCanvas.selection=!1;drawingCanvas.freeDrawingBrush=new fabric.PencilBrush(drawingCanvas);drawingCanvas.freeDrawingBrush.color=
hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvas.freeDrawingBrush.width=parseInt(e,10)||10;drawingCanvas.renderAll();drawingCanvasOnepage.isDrawingMode=!0;drawingCanvasOnepage.selection=!1;drawingCanvasOnepage.freeDrawingBrush=new fabric.PencilBrush(drawingCanvasOnepage);drawingCanvasOnepage.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvasOnepage.freeDrawingBrush.width=parseInt(e,10)||10;drawingCanvasOnepage.renderAll();hideTextAlert();setPenMenu(3)};document.getElementById("btn_drawing_eraser").onclick=
function(){setSelectionMode(!0);hideTextAlert();setPenMenu(4)};document.getElementById("btn_drawing_eraserall").onclick=function(){drawingCanvas.clear();drawingCanvasOnepage.clear();saveDrawingData();drawingCanvas.selection?(setSelectionMode(!0),setPenMenu(4)):(drawingCanvas.selection=!1,drawingCanvasOnepage.selection=!1)};document.getElementById("btn_drawing_linewidth1").onclick=function(){e=1;drawingCanvas.freeDrawingBrush.width=e;drawingCanvasOnepage.freeDrawingBrush.width=e;setLineWidth(1)};document.getElementById("btn_drawing_linewidth2").onclick=
function(){e=10;drawingCanvas.freeDrawingBrush.width=e;drawingCanvasOnepage.freeDrawingBrush.width=e;setLineWidth(2)};document.getElementById("btn_drawing_linewidth3").onclick=function(){e=20;drawingCanvas.freeDrawingBrush.width=e;drawingCanvasOnepage.freeDrawingBrush.width=e;setLineWidth(3)};document.getElementById("btn_drawing_linewidth4").onclick=function(){e=30;drawingCanvasOnepage.freeDrawingBrush.width=e;drawingCanvas.freeDrawingBrush.width=e;setLineWidth(4)};d.onchange=function(){drawingCanvasOnepage.freeDrawingBrush.color=
hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100)};alphaSlider=document.getElementById("drawing-alpha");noUiSlider.create(alphaSlider,{start:[100],step:1,orientation:"horizontal",range:{min:[1],max:[Number(100)]},tooltips:!1});alphaSlider.noUiSlider.on("update",function(a,b){drawingAlphaValue=parseInt(a);setAlpha(drawingAlphaValue);drawingCanvas.isDrawingMode&&(drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/
100));drawingCanvasOnepage.isDrawingMode&&(drawingCanvasOnepage.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100))});drawingCanvas.freeDrawingBrush&&(drawingCanvas.freeDrawingBrush.color=d.value,drawingCanvas.freeDrawingBrush.width=parseInt(e,10)||1,drawingCanvas.freeDrawingBrush.shadowBlur=0);drawingCanvasOnepage.freeDrawingBrush&&(drawingCanvasOnepage.freeDrawingBrush.color=d.value,drawingCanvasOnepage.freeDrawingBrush.width=parseInt(e,10)||1,drawingCanvasOnepage.freeDrawingBrush.shadowBlur=
0);drawingCanvas.on("mouse:down",function(a){t=!0;u=!1;if(!drawingCanvas.isDrawingMode&&!drawingCanvas.selection){a=drawingCanvas.getPointer(a.e);var v=[a.x,a.y,a.x,a.y];b=a.x;g=a.y;"line"==f?(u=!0,l=new fabric.Line(v,{strokeWidth:e,fill:d.value,stroke:d.value,originX:"center",originY:"center",opacity:drawingAlphaValue/100}),drawingCanvas.add(l)):"triangle"==f?(m=new fabric.Triangle({left:a.x,top:a.y,fill:d.value,width:5,height:5,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,opacity:drawingAlphaValue/
100}),drawingCanvas.add(m)):"rect"==f?(n=new fabric.Rect({width:5,height:5,left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(n)):"pentagon"==f?(p=new fabric.Polygon(regularPolygonPoints(5,5,a.x,a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(p)):"hexagon"==f?(q=new fabric.Polygon(regularPolygonPoints(6,5,a.x,
a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(q)):"circle"==f&&(r=new fabric.Circle({radius:5,left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(r))}});drawingCanvas.on("mouse:move",function(a){if(t&&!drawingCanvas.isDrawingMode&&!drawingCanvas.selection){a=drawingCanvas.getPointer(a.e);if("line"==f)l.set({x2:a.x,
y2:a.y});else if("triangle"==f)m.set({width:Math.abs(2*(a.x-b)),height:Math.abs(2*(a.y-g))});else if("rect"==f)n.set({width:Math.abs(2*(a.x-b)),height:Math.abs(2*(a.y-g))});else if("pentagon"==f){a=regularPolygonPoints(5,Math.abs(a.x-b),b,g);for(var d,e=0,k,h=0,c=0;c<a.length;c++)d=0==c?a[c].x:Math.min(d,a[c].x),e=Math.max(e,a[c].x),k=0==c?a[c].y:Math.min(k,a[c].y),h=Math.max(h,a[c].y);p.set({width:e-d,height:h-k,points:a})}else if("hexagon"==f){a=regularPolygonPoints(6,Math.abs(a.x-b),b,g);for(c=
h=e=0;c<a.length;c++)d=0==c?a[c].x:Math.min(d,a[c].x),e=Math.max(e,a[c].x),k=0==c?a[c].y:Math.min(k,a[c].y),h=Math.max(h,a[c].y);q.set({width:e-d,height:h-k,points:a})}else"circle"==f&&r.set({radius:Math.abs(2*(a.x-b))});drawingCanvas.renderAll()}});drawingCanvas.on("mouse:up",function(a){t=!1;saveDrawingData();u&&loadDrawData();u=!1});drawingCanvasOnepage.on("mouse:down",function(a){t=!0;if(!drawingCanvasOnepage.isDrawingMode&&!drawingCanvasOnepage.selection){a=drawingCanvasOnepage.getPointer(a.e);
var v=[a.x,a.y,a.x,a.y];b=a.x;g=a.y;"line"==f?(l=new fabric.Line(v,{strokeWidth:e,fill:d.value,stroke:d.value,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(l)):"triangle"==f?(m=new fabric.Triangle({left:a.x,top:a.y,fill:d.value,width:5,height:5,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(m)):"rect"==f?(n=new fabric.Rect({width:5,height:5,left:a.x,top:a.y,
originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(n)):"pentagon"==f?(p=new fabric.Polygon(regularPolygonPoints(5,5,a.x,a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(p)):"hexagon"==f?(q=new fabric.Polygon(regularPolygonPoints(6,5,a.x,a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,
fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(q)):"circle"==f&&(r=new fabric.Circle({radius:5,left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvasOnepage.add(r))}});drawingCanvasOnepage.on("mouse:move",function(a){if(t&&!drawingCanvasOnepage.isDrawingMode&&!drawingCanvasOnepage.selection){a=drawingCanvasOnepage.getPointer(a.e);if("line"==f)l.set({x2:a.x,y2:a.y});else if("triangle"==f)m.set({width:Math.abs(2*
(a.x-b)),height:Math.abs(2*(a.y-g))});else if("rect"==f)n.set({width:Math.abs(2*(a.x-b)),height:Math.abs(2*(a.y-g))});else if("pentagon"==f){a=regularPolygonPoints(5,Math.abs(a.x-b),b,g);for(var e,d=0,k,h=0,c=0;c<a.length;c++)e=0==c?a[c].x:Math.min(e,a[c].x),d=Math.max(d,a[c].x),k=0==c?a[c].y:Math.min(k,a[c].y),h=Math.max(h,a[c].y);p.set({width:d-e,height:h-k,points:a})}else if("hexagon"==f){a=regularPolygonPoints(6,Math.abs(a.x-b),b,g);for(c=h=d=0;c<a.length;c++)e=0==c?a[c].x:Math.min(e,a[c].x),
d=Math.max(d,a[c].x),k=0==c?a[c].y:Math.min(k,a[c].y),h=Math.max(h,a[c].y);q.set({width:d-e,height:h-k,points:a})}else"circle"==f&&r.set({radius:Math.abs(2*(a.x-b))});drawingCanvasOnepage.renderAll()}});drawingCanvasOnepage.on("mouse:up",function(a){t=!1;saveDrawingData()})})();
