var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,b,c){if(e){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in b||(b[d]={});b=b[d]}a=a[a.length-1];c=b[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,c){var d=this.length||0;0>b&&(b=Math.max(0,d+b));if(null==c||c>d)c=d;c=Number(c);0>c&&(c=Math.max(0,d+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}},"es6","es3");
var keyword="",selectedKeyword="",highlightRects=[];function Rect(a,e,b,c){var d,f,g,h;this.x=a;this.y=e;this.width=b;this.height=c;this.set=function(a,d,b,c){this.x=a;this.y=d;this.width=b;this.height=c};this.contains=function(a,b,c,e){d=Math.max(this.x,a);f=Math.min(this.x+this.width,a+c);g=Math.max(this.y,b);h=Math.min(this.y+this.height,b+e);return d<f&&g<h}}function Point(){this.y=this.x=0}
function Words(a){this.min=new Point;this.max=new Point;this.height=this.width=0;this.min.x=a[4]*svgViewBox.scale;this.max.x=(a[4]+a[6])*svgViewBox.scale;this.min.y=(a[5]-a[6])*svgViewBox.scale;this.max.y=a[5]*svgViewBox.scale;this.width=a[6]*svgViewBox.scale;this.height=a[6]*svgViewBox.scale}
function draggingHighlight(a){highlightRects=[];var e="";this.push=function(a,b,d,c){highlightRects.push(new HighlightRect(parseFloat(a),parseFloat(b),parseFloat(d),parseFloat(c)))};for(var b=0;b<epubDB.pageInfo.length;b++)if(null!=epubDB.pageInfo[b].matrix)for(var c=0;c<epubDB.pageInfo[b].matrix.length;c++){var d=new Words(epubDB.pageInfo[b].matrix[c]);var f=parseFloat(d.min.x)+viewBox.w*b,g=parseFloat(d.min.y),h=parseFloat(d.width);d=parseFloat(d.height);if(a.contains(f,g,h,d))if(e+=epubDB.pageInfo[b].contents[c],
0==highlightRects.length)this.push(f,g,h,d);else{for(var k=!1,l=0;l<highlightRects.length;l++)if(highlightRects[l].contains(f,g,h,d)){k=!0;break}k||this.push(f,g,h,d)}}for(c=b=a=0;c<highlightRects.length;c++)highlightRects[c].draw(hl_context),a=Math.max(a,highlightRects[c].x+highlightRects[c].width),b=Math.max(b,highlightRects[c].y+highlightRects[c].height);selectedKeyword=e;console.log("mx : "+a+", my : "+b+", word : "+e);void 0!==window.viewer&&"undefined"!==typeof window.viewer.selectedText?(window.viewer.selectedText(e),
disableHighlight()):0<e.length?$("#popupTextSelector").show():($("#popupTextSelector").hide(),disableHighlight(),showSnackBar("snackbar_noselected"));$("#copiedText").val(e);return e}
function drawHighlight(){console.log("#Drawing Highlight");this.push=function(a,b,d,c){highlightRects.push(new HighlightRect(a,b,d,c))};highlightRects=[];hl_context.globalAlpha=.5;hl_context.clearRect(0,0,hl_canvas.width,hl_canvas.height);for(var a,e=0,b=0;b<epubDB.pageInfo.length;b++)for(var c=e=0;;){a=epubDB.pageInfo[b].contents.indexOf(keyword,e);e=a+keyword.length-1;if(0>a)break;if(100<++c)break;for(var d=0;d<keyword.length;d++){var f=parseFloat(epubDB.pageInfo[b].matrix[a+d][4])*svgViewBox.scale+
viewBox.w*b,g=(parseFloat(epubDB.pageInfo[b].matrix[a+d][5])-parseFloat(epubDB.pageInfo[b].matrix[a+d][6]))*svgViewBox.scale,h=parseFloat(epubDB.pageInfo[b].matrix[a+d][6])*svgViewBox.scale,k=parseFloat(epubDB.pageInfo[b].matrix[a+d][6])*svgViewBox.scale;if(0==highlightRects.length)this.push(f,g,h,k);else{for(var l=!1,m=0;m<highlightRects.length;m++)if(highlightRects[m].contains(f,g,h,k)){l=!0;break}l||this.push(f,g,h,k)}}}for(d=0;d<highlightRects.length;d++)highlightRects[d].draw(hl_context)}
function HighlightRect(a,e,b,c){this.x=a;this.y=e;this.width=b;this.height=c;this.contains=function(a,b,c,e){if(this.y!=b)return!1;this.x>a&&(this.x=a);this.x+this.width<a+c&&(this.width=a+c-this.x);return!0};this.draw=function(a){a.beginPath();a.rect(this.x,this.y,this.width,this.height);a.fillStyle="#e8436c";a.fill();a.lineWidth=1;a.strokeStyle="#b0c2f7";a.stroke()}}$(document).ready(function(){});
