var drawingCanvas,drawingData=[];function openDrawer(){$("#tool_drawing").show();$("#cover_drawing").css("pointer-events","auto")}function closeDrawing(){$("#tool_drawing").hide();$("#cover_drawing").css("pointer-events","none");saveDrawingData()}function hexToRgbA(b,f){if(/^#([A-Fa-f0-9]{3}){1,2}$/.test(b))return b=b.substring(1).split(""),3==b.length&&(b=[b[0],b[0],b[1],b[1],b[2],b[2]]),b="0x"+b.join(""),"rgba("+[b>>16&255,b>>8&255,b&255].join()+", "+f+")";throw Error("Bad Hex");}
function handleImage(b){var f=new FileReader;f.onload=function(b){var f=new Image;f.onload=function(){var b=new fabric.Image(f,{top:100,left:100});drawingCanvas.add(b)};f.src=b.target.result};f.readAsDataURL(b.target.files[0])}
function loadDrawData(){drawingCanvas.clear();null!=localStorage.getItem("drawing_popup_"+escape(window.location.pathname).replace(/\//gi,"_"))&&(drawingData=JSON.parse(localStorage.getItem("drawing_popup_"+escape(window.location.pathname).replace(/\//gi,"_"))),null!=drawingData&&drawingCanvas.loadFromJSON(drawingData,function(){drawingCanvas.renderAll();disableSelectObject()}))}
function saveDrawingData(){localStorage.setItem("drawing_popup_"+escape(window.location.pathname).replace(/\//gi,"_"),JSON.stringify(drawingCanvas.toJSON()))}function disableSelectObject(){drawingCanvas.forEachObject(function(b){b.selectable=!1})}function setLineWidth(b){for(var f=1;5>f;f++)f==b?$("#btn_drawing_linewidth"+f).addClass("on"):$("#btn_drawing_linewidth"+f).removeClass("on")}
function selectedMenu(b){1==b?($("#btn_drawing_draw").removeClass("on"),$("#btn_drawing_selection").addClass("on"),$(".blush_line").addClass("select_line"),$(".drawing_disable").show()):($("#btn_drawing_draw").addClass("on"),$("#btn_drawing_selection").removeClass("on"),$(".blush_line").removeClass("select_line"),$(".drawing_disable").hide())}function setAlpha(b){$(".oper_value").text(b)}
function setPenMenu(b){switch(b){case 1:$("#btn_drawing_line").addClass("on");$("#btn_drawing_pencil").removeClass("on");$("#btn_drawing_highlight").removeClass("on");$("#btn_drawing_eraser").removeClass("on");setLineWidth(1);break;case 2:$("#btn_drawing_line").removeClass("on");$("#btn_drawing_pencil").addClass("on");$("#btn_drawing_highlight").removeClass("on");$("#btn_drawing_eraser").removeClass("on");setLineWidth(1);break;case 3:$("#btn_drawing_line").removeClass("on");$("#btn_drawing_pencil").removeClass("on");
$("#btn_drawing_highlight").addClass("on");$("#btn_drawing_eraser").removeClass("on");setLineWidth(4);break;case 4:$("#btn_drawing_line").removeClass("on"),$("#btn_drawing_pencil").removeClass("on"),$("#btn_drawing_highlight").removeClass("on"),$("#btn_drawing_eraser").addClass("on")}}
function setSelectionMode(b){b?(drawingCanvas.isDrawingMode=!1,drawingCanvas.selection=!0,drawingCanvas.forEachObject(function(b){b.selectable=!0})):(drawingCanvas.isDrawingMode=!1,drawingCanvas.selection=!1,drawingCanvas.forEachObject(function(b){b.selectable=!1}));drawingCanvas.renderAll()}
function resizeCanvas(){$("#cover_drawing").css("top",0);$("#cover_drawing").css("left",0);$("#cover_drawing").css("z-index",101);$("#cover_drawing").width(1440);$("#cover_drawing").height(980);$("#drawingCanvas").width(1440);$("#drawingCanvas").height(980);drawingCanvas.setWidth(1440);drawingCanvas.setHeight(980);drawingCanvas.renderAll()}
$(document).ready(function(){$("#btn_hide_drawing").click(function(){$("#cover_drawing").is(":visible")?($("#cover_drawing").hide(),$("#btn_hide_drawing").addClass("on")):($("#cover_drawing").show(),$("#btn_hide_drawing").removeClass("on"))});$("#drawing-color").spectrum({preferredFormat:"hex3",change:function(b){}});$("#tool_drawing").draggable();$(window).resize(function(){resizeCanvas()});resizeCanvas()});
(function(){var b,f,m,n,p,q,r,t,u,l,c=1,g="line";drawingCanvas=this.__canvas=new fabric.Canvas("drawingCanvas",{isDrawingMode:!1,selection:!1,preserveObjectStacking:!0});fabric.Object.prototype.transparentCorners=!1;fabric.Object.prototype.cornerSize=3;document.getElementById("drawing-mode-options");var d=document.getElementById("drawing-color");document.getElementById("btn_drawing_line").onclick=function(){setSelectionMode(!1);drawingCanvas.isDrawingMode=!1;drawingCanvas.selection=!1;g="line";c=
1;drawingCanvas.renderAll();setPenMenu(1)};drawingCanvas.on("object:selected",function(a){null!=drawingCanvas.getActiveObject()&&drawingCanvas.getActiveObject().remove()});document.getElementById("btn_drawing_pencil").onclick=function(){setSelectionMode(!1);c=1;drawingCanvas.isDrawingMode=!0;drawingCanvas.selection=!1;drawingCanvas.freeDrawingBrush=new fabric.PencilBrush(drawingCanvas);drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvas.freeDrawingBrush.width=
parseInt(c,1)||1;drawingCanvas.renderAll();setPenMenu(2)};document.getElementById("btn_drawing_highlight").onclick=function(){setSelectionMode(!1);c=30;drawingCanvas.isDrawingMode=!0;drawingCanvas.selection=!1;drawingCanvas.freeDrawingBrush=new fabric.PencilBrush(drawingCanvas);drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100);drawingCanvas.freeDrawingBrush.width=parseInt(c,10)||10;drawingCanvas.renderAll();setPenMenu(3)};document.getElementById("btn_drawing_eraser").onclick=
function(){setSelectionMode(!0);setPenMenu(4)};document.getElementById("btn_drawing_eraserall").onclick=function(){drawingCanvas.clear();saveDrawingData();drawingCanvas.selection?(setSelectionMode(!0),setPenMenu(4)):drawingCanvas.selection=!1};document.getElementById("btn_drawing_linewidth1").onclick=function(){c=1;drawingCanvas.freeDrawingBrush.width=c;setLineWidth(1)};document.getElementById("btn_drawing_linewidth2").onclick=function(){c=10;drawingCanvas.freeDrawingBrush.width=c;setLineWidth(2)};
document.getElementById("btn_drawing_linewidth3").onclick=function(){c=20;drawingCanvas.freeDrawingBrush.width=c;setLineWidth(3)};document.getElementById("btn_drawing_linewidth4").onclick=function(){c=30;drawingCanvas.freeDrawingBrush.width=c;setLineWidth(4)};d.onchange=function(){drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100)};alphaSlider=document.getElementById("drawing-alpha");noUiSlider.create(alphaSlider,{start:[100],step:1,orientation:"horizontal",range:{min:[1],
max:[Number(100)]},tooltips:!1});alphaSlider.noUiSlider.on("update",function(a,b){drawingAlphaValue=parseInt(a);setAlpha(drawingAlphaValue);drawingCanvas.isDrawingMode&&(drawingCanvas.freeDrawingBrush.color=hexToRgbA(d.value,drawingAlphaValue/100))});drawingCanvas.freeDrawingBrush&&(drawingCanvas.freeDrawingBrush.color=d.value,drawingCanvas.freeDrawingBrush.width=parseInt(c,10)||1,drawingCanvas.freeDrawingBrush.shadowBlur=0);drawingCanvas.on("mouse:down",function(a){u=!0;l=!1;if(!drawingCanvas.isDrawingMode&&
!drawingCanvas.selection){a=drawingCanvas.getPointer(a.e);var v=[a.x,a.y,a.x,a.y];b=a.x;f=a.y;"line"==g?(l=!0,m=new fabric.Line(v,{strokeWidth:c,fill:d.value,stroke:d.value,originX:"center",originY:"center",opacity:drawingAlphaValue/100}),drawingCanvas.add(m)):"triangle"==g?(n=new fabric.Triangle({left:a.x,top:a.y,fill:d.value,width:5,height:5,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,opacity:drawingAlphaValue/100}),drawingCanvas.add(n)):"rect"==g?(p=new fabric.Rect({width:5,
height:5,left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(p)):"pentagon"==g?(q=new fabric.Polygon(regularPolygonPoints(5,5,a.x,a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(q)):"hexagon"==g?(r=new fabric.Polygon(regularPolygonPoints(6,5,a.x,a.y),{left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,
hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(r)):"circle"==g&&(t=new fabric.Circle({radius:5,left:a.x,top:a.y,originX:"center",originY:"center",hasControls:!1,hasBorders:!1,fill:d.value,opacity:drawingAlphaValue/100}),drawingCanvas.add(t))}});drawingCanvas.on("mouse:move",function(a){if(u&&!drawingCanvas.isDrawingMode&&!drawingCanvas.selection){a=drawingCanvas.getPointer(a.e);if("line"==g)m.set({x2:a.x,y2:a.y});else if("triangle"==g)n.set({width:Math.abs(2*(a.x-b)),
height:Math.abs(2*(a.y-f))});else if("rect"==g)p.set({width:Math.abs(2*(a.x-b)),height:Math.abs(2*(a.y-f))});else if("pentagon"==g){a=regularPolygonPoints(5,Math.abs(a.x-b),b,f);for(var c,d=0,k,h=0,e=0;e<a.length;e++)c=0==e?a[e].x:Math.min(c,a[e].x),d=Math.max(d,a[e].x),k=0==e?a[e].y:Math.min(k,a[e].y),h=Math.max(h,a[e].y);q.set({width:d-c,height:h-k,points:a})}else if("hexagon"==g){a=regularPolygonPoints(6,Math.abs(a.x-b),b,f);for(e=h=d=0;e<a.length;e++)c=0==e?a[e].x:Math.min(c,a[e].x),d=Math.max(d,
a[e].x),k=0==e?a[e].y:Math.min(k,a[e].y),h=Math.max(h,a[e].y);r.set({width:d-c,height:h-k,points:a})}else"circle"==g&&t.set({radius:Math.abs(2*(a.x-b))});drawingCanvas.renderAll()}});drawingCanvas.on("mouse:up",function(a){u=!1;saveDrawingData();l&&loadDrawData();l=!1});loadDrawData()})();
